jobs: 
- deployment: VMDeploy
  displayName: web
  environment:
    name: prod
    resourceType: VirtualMachine
  strategy:
      rolling:
        maxParallel: 2  #for percentages, mention as x%
        preDeploy:
          steps:
          - download: current
            artifact: drop
          - script: echo initialize, cleanup, backup, install certs
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                docker run -d --name=c1 -p 9090:80 docker.io/httpd
        